-- Criando o banco de dados app_pizzaria

-------------------------------- CADASTRO FUNCIONÁRIOS --------------------------------------------------------
CREATE DATABASE APP_PIZZARIA;
USE APP_PIZZARIA;

-- Criando tabela CADASTRO_FUNCIONARIOS
CREATE TABLE CADASTRO_FUNCIONARIO (
    ID INT IDENTITY (1,1) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    CARGO VARCHAR (255) NOT NULL,
    SENHA VARCHAR (255) NOT NULL,
	SALARIO INT NOT NULL,
	HORARIO varchar(255) NOT NULL,
	EMAIL VARCHAR (255) NOT NULL,
);

-- Criando tabela FUNCIONARIOS com chave estrangeira para CADASTRO_FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
    ID INT PRIMARY KEY,  -- Chave estrangeira para CADASTRO_FUNCIONARIOS
    NOME VARCHAR(255) NOT NULL,
    CARGO VARCHAR(255) NOT NULL,
    SALARIO INT NOT NULL,
	 HORARIO VARCHAR(255) NOT NULL,
	EMAIL VARCHAR (255) NOT NULL,
    FOREIGN KEY (ID) REFERENCES CADASTRO_FUNCIONARIO(id)
);


-- Criando o trigger para inserir automaticamente na tabela FUNCIONARIOS
CREATE TRIGGER tr_CadastroFuncionarios_Insert
ON CADASTRO_FUNCIONARIO
AFTER INSERT
AS
BEGIN
    INSERT INTO FUNCIONARIOS (ID, NOME, CARGO, HORARIO, SALARIO , EMAIL)
    SELECT ID, NOME, CARGO, HORARIO, SALARIO , EMAIL
    FROM INSERTED;
END;


-- Inserindo dados na tabela CADASTRO_FUNCIONARIOS
INSERT INTO CADASTRO_FUNCIONARIO (NOME, CARGO, SENHA, SALARIO, HORARIO , EMAIL)
VALUES ('LUCAS DA SILVA JORDANO', 'CHEFE', '123', 1500, '8:00 as 18:00', 'LUCASJORDANO@GMAIL.COM');

INSERT INTO CADASTRO_FUNCIONARIO (NOME, CARGO, SENHA, SALARIO, HORARIO , EMAIL)
VALUES ('ANDRESSA GILIOLI DO CARMOS SILVA', 'CHEFE', '123', 1500, '8:00 as 18:00','ANDRESSAGILIOLI@GMAIL.COM');

-- Verificando a tabela FUNCIONARIOS
SELECT * FROM CADASTRO_FUNCIONARIO;
SELECT * FROM FUNCIONARIOS;


-- Excluindo a tabela FUNCIONARIOS (opcional)
DROP TABLE FUNCIONARIOS;
DROP TABLE CADASTRO_FUNCIONARIO;
----------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------CARDÁPIO--------------------------------------------------------------------------

-- Criando tabela CADASTRO_FUNCIONARIOS
CREATE TABLE PRODUTOS (
    ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME_PRODUTO VARCHAR(255),
	TIPO_PRODUTO VARCHAR(255),
	PRECO_PRODUTO VARCHAR(255)
);



SELECT * FROM PRODUTOS;
DROP TABLE PRODUTO;
DROP TABLE CADASTRO_PRODUTO;

DELETE FROM CADASTRO_PRODUTO
WHERE ID = 149;